import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { TrendTable } from "@/components/TrendTable";
import {
  GENRE_OPTIONS,
  VIBE_OPTIONS,
  getCollectionBySlug,
  resolveCategoryFromSlug,
} from "@/lib/categories";
import { getAudioByGenre, getAudioByVibe } from "@/lib/db";
import { buildCanonical, buildFaqSchema } from "@/lib/seo";

export const runtime = "edge";
export const revalidate = 900;

interface PageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const meta = buildCollectionMeta(slug);
  if (!meta) return {};
  return {
    title: meta.title,
    description: meta.description,
    alternates: {
      canonical: buildCanonical(`/trends/${slug}`),
    },
    openGraph: {
      title: meta.title,
      description: meta.description,
      url: buildCanonical(`/trends/${slug}`),
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: meta.title,
      description: meta.description,
    },
  };
}

export default async function TrendCollectionPage({ params }: PageProps) {
  const { slug } = await params;
  const meta = buildCollectionMeta(slug);
  if (!meta) notFound();

  const trends = meta.genre
    ? await getAudioByGenre(meta.genre, 50)
    : meta.vibe
      ? await getAudioByVibe(meta.vibe, 50)
      : [];

  return (
    <div className="mx-auto w-full max-w-6xl px-6 pb-16 pt-12">
      <section className="space-y-4">
        <p className="text-xs uppercase tracking-[0.3em] text-black/50">
          Trend collection
        </p>
        <h1 className="font-display text-3xl font-semibold md:text-4xl">
          {meta.title}
        </h1>
        <p className="max-w-2xl text-sm text-black/60">{meta.description}</p>
      </section>

      <section className="mt-10">
        <TrendTable data={trends} />
      </section>

      <script
        type="application/ld+json"
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(
            buildFaqSchema([
              {
                question: `What makes the ${meta.title} list?`,
                answer:
                  "Entries rank by current TikTok chart position and growth rate calculated from play count deltas.",
              },
              {
                question: "How fresh is this collection?",
                answer:
                  "Data refreshes every six hours and this page revalidates every 15 minutes for fast cache updates.",
              },
              {
                question: "Can I request a new collection?",
                answer:
                  "Yes—submit a request via the contact link and we will add a curated slug that maps to your vibe or genre.",
              },
            ]),
          ),
        }}
      />
    </div>
  );
}

function buildCollectionMeta(slug: string) {
  const collection = getCollectionBySlug(slug);
  if (collection) return collection;

  const resolved = resolveCategoryFromSlug(slug);
  if (!resolved.genre && !resolved.vibe) return null;

  const genre = resolved.genre
    ? GENRE_OPTIONS.find((option) => option.slug === resolved.genre)
    : null;
  const vibe = resolved.vibe
    ? VIBE_OPTIONS.find((option) => option.slug === resolved.vibe)
    : null;

  return {
    slug,
    title: genre
      ? `${genre.label} TikTok Trends`
      : vibe
        ? `${vibe.label} TikTok Trends`
        : "TikTok Trends",
    description:
      genre?.description ??
      vibe?.description ??
      "Trend collection generated by GramDominator.",
    genre: genre?.slug,
    vibe: vibe?.slug,
  };
}

export const dynamicParams = true;
